import mysql.connector
import pandas as pd
import streamlit as st
# Conexión a la base de datos MySQL
conexion = mysql.connector.connect(
host="localhost",
user="root      ",
password="", 
database="bd_lavadora"
)              
df_clientes = pd.read_sql("SELECT * FROM cliente", con=conexion)
st.title("Unidad 2: Preparación de Datos")
st.dataframe(df_clientes)
st.header("Muestra las primeras filas del Dataframe")
st.dataframe(df_clientes)
st.header("Muestra las últimas filas del Dataframe")
st.dataframe(df_clientes.tail())
st.header("Muestra la información general del Dataframe")
st.write(df_clientes.info())
st.header("Muestra las estadísticas descriptivas del Dataframe")
st.dataframe(df_clientes.describe())
st.header("Muestra valores nulos por columna")
st.write(df_clientes.isnull().sum())
st.header("Muestra el número de filas y columnas del Dataframe")
st.write(df_clientes.shape)
st.header("Muestra el número de filas duplicadas en el Dataframe")
st.write(df_clientes.duplicated().sum())
st.header("Muestra los tipos de datos de cada columna")
st.dataframe(df_clientes.dtypes)
st.header("Muestra el número de valores únicos por columna")
st.dataframe(df_clientes.nunique())
st.title("Unidad 3: Limpieza de Datos")
st.header("1. identificar valores nulos")
st.write(df_clientes.isnull().sum())
st.header("Mostrar los registros con valores nulos")
st.dataframe(df_clientes[df_clientes.isnull().any(axis=1)])
st.header("2. Elimina filas con valores nulos")
df_limpio=df_clientes.dropna()
st.dataframe(df_limpio)
st.header("Agregar un valor por defecto a los valores nulos")
df_clientes=df_clientes.fillna("Desconocido")
st.dataframe(df_clientes)
st.header("agregar la media a los valores nulos en una columna numérica")
df_clientes["tipo_identificacion_id"].fillna(df_clientes["tipo_identificacion_id"].mean(), inplace=True)
st.dataframe(df_clientes)
st.header("Numero de filas duplicadas")
st.write(df_clientes.duplicated().sum())
st.header("Eliminar filas duplicadas")
df_clientes=df_clientes.drop_duplicates()
st.dataframe(df_clientes)
#Agregar una nueva columna ventas de manera aleatorea
import numpy as np
df_clientes["ventas"] = np.random.randint(1000, 5000, size=len(df_clientes))
st.dataframe(df_clientes)
st.header("Valores atípicos en la columna ventas")
st.dataframe(df_clientes[df_clientes["ventas"] > 4000])
st.write("Número de valores atípicos en la columna ventas:", df_clientes[df_clientes["ventas"] > 4000].shape[0])
st.header("Eliminar valores atípicos en la columna ventas")
df_clientes=df_clientes[df_clientes["ventas"] <= 4000]
st.dataframe(df_clientes)
st.header("Convertir la columna fecha_nacimiento a formato datetime")
df_clientes["fecha_registro"] = pd.to_datetime(df_clientes["fecha_registro"])
st.dataframe(df_clientes)
st.header("Renombrar columnas")
df_clientes.rename(columns={"nombre": "Nombre", "apellido": "Apellido", "fecha_registro": "Fecha de Nacimiento"}, inplace=True)
st.dataframe(df_clientes)
st.header("Mostrar el resultado final")
st.dataframe(df_clientes.shape)
st.dataframe(df_clientes.describe())
st.title("uardar datos limpios a un archivo csv")
df_clientes.to_csv("clientes_limpios.csv", index=False)
st.write("Datos limpios guardados en clientes_limpios.csv")